-- Create AuditLogs table directly
-- Run this in psql or your Postgres client

CREATE TABLE IF NOT EXISTS "AuditLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer,
    "UserName" character varying(200) NOT NULL DEFAULT 'System',
    "UserRole" character varying(100) NOT NULL DEFAULT '',
    "Action" character varying(50) NOT NULL,
    "Module" character varying(100) NOT NULL,
    "EntityId" integer,
    "EntityName" character varying(200),
    "OldValues" text,
    "NewValues" text,
    "ChangeSummary" character varying(1000),
    "IpAddress" character varying(45),
    "IsSystemAction" boolean NOT NULL DEFAULT false,
    "Timestamp" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);

-- Index for common query patterns
CREATE INDEX IF NOT EXISTS "IX_AuditLogs_Timestamp" ON "AuditLogs" ("Timestamp" DESC);
CREATE INDEX IF NOT EXISTS "IX_AuditLogs_Module" ON "AuditLogs" ("Module");
CREATE INDEX IF NOT EXISTS "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AuditLogs_Action" ON "AuditLogs" ("Action");

-- Register in EF migration history so dotnet ef database update stays in sync
-- (Replace the migration ID below with the actual one from Migrations/xxx_AddAuditLog.cs)
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260429_AddAuditLog', '9.0.8'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" LIKE '%AddAuditLog%'
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260429_SyncModelSnapshot', '9.0.8'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" LIKE '%SyncModelSnapshot%'
);
