using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using AvyyanBackend.Data;

#nullable disable

namespace AvyyanBackend.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429062000_AddAuditLog")]
    public partial class AddAuditLog : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
ALTER TABLE ""ProductionAllotments""
    ADD COLUMN IF NOT EXISTS ""PolybagColor"" character varying(100) NOT NULL DEFAULT '';

ALTER TABLE ""ProductionAllotments""
    ADD COLUMN IF NOT EXISTS ""ProductionStatus"" integer NOT NULL DEFAULT 0;

ALTER TABLE ""ProductionAllotments""
    ADD COLUMN IF NOT EXISTS ""YarnPartyName"" character varying(200) NOT NULL DEFAULT '';

CREATE TABLE IF NOT EXISTS ""AuditLogs"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""UserId"" integer NULL,
    ""UserName"" character varying(200) NOT NULL DEFAULT 'System',
    ""UserRole"" character varying(100) NOT NULL DEFAULT '',
    ""Action"" character varying(50) NOT NULL,
    ""Module"" character varying(100) NOT NULL,
    ""EntityId"" integer NULL,
    ""EntityName"" character varying(200) NULL,
    ""OldValues"" text NULL,
    ""NewValues"" text NULL,
    ""ChangeSummary"" character varying(1000) NULL,
    ""IpAddress"" character varying(45) NULL,
    ""IsSystemAction"" boolean NOT NULL DEFAULT false,
    ""Timestamp"" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT ""PK_AuditLogs"" PRIMARY KEY (""Id"")
);

CREATE INDEX IF NOT EXISTS ""IX_AuditLogs_Timestamp"" ON ""AuditLogs"" (""Timestamp"");
CREATE INDEX IF NOT EXISTS ""IX_AuditLogs_Module"" ON ""AuditLogs"" (""Module"");
CREATE INDEX IF NOT EXISTS ""IX_AuditLogs_UserId"" ON ""AuditLogs"" (""UserId"");
");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "AuditLogs");

            migrationBuilder.DropColumn(name: "PolybagColor", table: "ProductionAllotments");
            migrationBuilder.DropColumn(name: "ProductionStatus", table: "ProductionAllotments");
            migrationBuilder.DropColumn(name: "YarnPartyName", table: "ProductionAllotments");
        }
    }
}
