using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace AvyyanBackend.Models
{
    /// <summary>
    /// Immutable record of every meaningful state change in the system.
    /// Rows in this table should NEVER be updated or deleted.
    /// </summary>
    public class AuditLog
    {
        [Key]
        public long Id { get; set; }

        // ── Who ──────────────────────────────────────────────────────────
        /// <summary>FK to Users table. Null for unauthenticated or system actions.</summary>
        public int? UserId { get; set; }

        /// <summary>
        /// Denormalized snapshot of the user's full name at the time of the action.
        /// Stored separately so renaming a user doesn't corrupt historical logs.
        /// </summary>
        [MaxLength(200)]
        public string UserName { get; set; } = "System";

        /// <summary>Denormalized role snapshot at the time of the action.</summary>
        [MaxLength(100)]
        public string UserRole { get; set; } = string.Empty;

        // ── What ─────────────────────────────────────────────────────────
        /// <summary>Action performed. E.g. CREATE, UPDATE, DELETE, CANCEL, LOGIN, LOGOUT, etc.</summary>
        [Required]
        [MaxLength(50)]
        public string Action { get; set; } = string.Empty;

        /// <summary>
        /// High-level module/domain name. E.g. "SalesOrder", "DispatchPlanning", "Auth".
        /// Used as the primary grouping dimension for filtering.
        /// </summary>
        [Required]
        [MaxLength(100)]
        public string Module { get; set; } = string.Empty;

        /// <summary>Primary key of the entity that was affected. Null for non-entity events (login/logout).</summary>
        public int? EntityId { get; set; }

        /// <summary>
        /// Human-readable label of the entity. E.g. "SO-1023", "DO-204", "Roll #45".
        /// Allows meaningful display even if the original record is later deleted.
        /// </summary>
        [MaxLength(200)]
        public string? EntityName { get; set; }

        // ── Change Detail ────────────────────────────────────────────────
        /// <summary>
        /// JSON string of ONLY the changed fields before the change.
        /// For CREATE events this is null. For high-risk events (CANCEL, DELETE) this is the full record snapshot.
        /// </summary>
        [Column(TypeName = "text")]
        public string? OldValues { get; set; }

        /// <summary>
        /// JSON string of ONLY the changed fields after the change.
        /// For DELETE/CANCEL events this is null.
        /// </summary>
        [Column(TypeName = "text")]
        public string? NewValues { get; set; }

        /// <summary>
        /// Plain English description of what changed. Auto-generated or manually set.
        /// E.g. "Quantity changed from 500 to 450 kg"
        /// </summary>
        [MaxLength(1000)]
        public string? ChangeSummary { get; set; }

        // ── Context ──────────────────────────────────────────────────────
        /// <summary>Client IP address at the time of the request.</summary>
        [MaxLength(45)] // IPv6 max length
        public string? IpAddress { get; set; }

        /// <summary>True if this log was generated by an automated system/background job rather than a human user.</summary>
        public bool IsSystemAction { get; set; } = false;

        // ── When ─────────────────────────────────────────────────────────
        [Column(TypeName = "timestamp with time zone")]
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }
}
